---
title: "Heat_Map_Challenge"
author: "Fay"
date: "28/03/2022"
output: html_document
---

```{r setup, include=FALSE}

```
## Pheatmap out of the data of challenge infections

These are my first steps to visualize the data out of the compiled challenge 
infections.

I have been following the tutorials: https://www.youtube.com/watch?v=pTeTH9bz-_s
https://towardsdatascience.com/pheatmap-draws-pretty-heatmaps-483dab9a3cc

### Load the necessary libraries
```{r, recho=FALSE}
library(pheatmap)
library(tidyverse)
library(matrixStats)
library(tidyr)
library(janitor)
library(tibble)
```

### Import the data:
```{r, echo=FALSE}
Challenge <- read.csv("https://raw.githubusercontent.com/derele/Eimeria_Lab/master/data_products/Challenge_infections.csv")
```

### Clean and prepare the data:
```{r, echo=FALSE}
df <- Challenge %>% 
  select(c("EH_ID", "primary_infection", "Position", "challenge_infection", "infection", "infection_history", "experiment","dpi", "CD4", "Treg", "Div_Treg", "Treg17", "Th1", "Div_Th1", "Th17", 
                    "Div_Th17", "CD8", "Act_CD8", "Div_Act_CD8", "IFNy_CD4", "IFNy_CD8", "Treg_prop", "IL17A_CD4", "mouse_strain", "relative_weight"))

#Replace the na in position with mln
df$Position[is.na(df$Position)] <- "mLN"

#select the measurements from the mesenterial lymphnodes
df_mln <- df %>% filter(Position == "mLN") %>%
  select(-c("Treg_prop", "IL17A_CD4")) #remove columns with NAs

#remove the rows that only contain nas
df_mln <- df_mln[complete.cases(df_mln), ]  

#select the columns necessary for the annotation columns
annotation_df <- df_mln %>% select(c("EH_ID", "primary_infection", 
                                     "challenge_infection", "infection_history",
                                     "mouse_strain", "relative_weight"))

#drop the unecessary columns
df_mln <- df_mln %>% select(-c(primary_infection, challenge_infection,dpi, infection, experiment, Position, mouse_strain, relative_weight))

#turn the data frame into a matrix 
## and transpose it. We want to have each cell type as a row name 
df_mln <- t(as.matrix(df_mln))

#switch the matrix back to a data frame format
df_mln <- as.data.frame(df_mln)

#turn the first row into column names
df_mln %>%
  row_to_names(row_number = 1) -> df_mln


#Now further prepare the data frame for plotting by removing the first row
## and convert the column to row names with the cells 
df_mln[-1, ] -> heatmap_data

#How do our data look like?
glimpse(heatmap_data) #alll columns appear to be numeric

#turn the columns to numeric other wise the heatmap function will not work
heatmap_data[] <- lapply(heatmap_data, function(x) as.numeric(as.character(x)))

```

### Prepare the annotation columns for the heatmap
```{r}
annotation_df
rownames(annotation_df) <- annotation_df$EH_ID
#remove the extra column
annotation_df <- annotation_df %>% select(-EH_ID, )
rownames(annotation_df) <- colnames(df_mln)

```
### Heatmap heat heat map
```{r}
#create the heatmap with the infection history as the annotation

png("heatmap_facs.png", width = 12, height = 12)
heatmap_data %>% 
  pheatmap(annotation_col = annotation_df, scale = "row")
dev.off()


```


