---
title: "Eimeria detection in tissue by qPCR"
author: "Fay"
date: "23/01/2022"
Included in Publication: "Víctor Hugo Jarquín-Díaz, Alice Balard, Jenny Jost, Julia Kraft, Mert Naci Dikmen, Jana Kvičerová Emanuel Heitlinger, Detection and quantification of house mouse Eimeria at the species level – Challenges and solutions for the assessment of coccidia in wildlife, International Journal for Parasitology. Parasites and Wildlife, Volume 10, 2019, https://doi.org/10.1016/j.ijppaw.2019.07.00"
output: 
    html_document:
        theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Quantitative real-time PCR for tissue samples

## Eimeria specific primers: 


1. Eim_COI_qX_F 5’-TGTCTATTCACTTGGGCTATTGT-3’ 
2. Eim_COI_qX_R 5’-GGA TCACCGTTAAATGAGGCA-3’

### Each reaction contains: (20 µL)

* 1X iTaqTM Universal SYBR® Green Supermix (Bio-Rad Laboratories GmbH, München, Germany)
* 400 nM forward and reverse primers 
* 50 ng template gDNA 

### PCR machine:

* Cycling in a Mastercycler® RealPlex 2 (Eppendorf, Hamburg, Germany) 

### Material used:

DNAs from tissue samples (Caecum / Jejunum)


### Cycling conditions:


1. initial denaturation at **95°C** for **2 min**
2. **40 cycles** of denaturation at **95°C** for **15 s**
3. annealing at **55 °C** for **15 s** 
4. and extension at **68°** for **20 s** 

(with data collection at the end of each cycle)

### Melting curve anaylsis:

Melting curves were analysed to detect eventual primer dimer formation or non-specific amplification. As internal reference for relative quantification the CDC42 gene from the nuclear genome of the house mouse was amplified (Ms_gDNA_CDC42_F CTCTCCTCCCCTCTGTCTTG; Ms_gDNA_CDC42_R TCCTTTTGGGTTGAGTTTCC).

Infection intensity was estimated as the ΔCt between mouse and Eimeria amplification (CtMouse- CtEimeria). 

To correct for background noise a detection threshold was estimated at "ΔCt = −5" and only results above this value were considered infected
### Positioning on the plate

Amplifications were performed by triplicate and each run included a non-template control (NTC). 


### Analysis and interpretation

In samples positive for qPCR, Eimeria genotyping was performed based on DNA extracted from tissue, as described above (see 2.4).